### ISSUE TITLE
Signed request expected

### ISSUE THREAD

**Issue by baum1234** [AsamK/JodelJS#10]
Hey,

when creating a new account I get the following message: Signed request expected

I'm using the current App Version und Secret: 5.16.1:TNHfHCaBjTvtrjEFsAFQyrHapTHdKbJVcraxnTzd

Is there something wrong?

**Comment by AsamK** [comment]
yeah, looks like something changed.

**Comment by baum1234** [comment]
are you going to fix it?

**Comment by AsamK** [comment]
When I have the time, to figure out what changed, I'll fix it ;)

**Comment by AsamK** [comment]
fixed now in 5b8ea15f9e6a58c2b4d7f200eb19e8e21b4b6f53
