### ISSUE TITLE
New secret for HMAC encryption

### ISSUE THREAD

**Issue by asd9** [AsamK/JodelJS#3]
What happens if the used secret (key) for hmac encryption is outdatet?
New accounts can't be created then..

**Comment by AsamK** [comment]
yeah, you have to regularly update the secret, there's a new Jodel version every week...
The author of OJOC is always very quick at finding the new keys:
https://bitbucket.org/cfib90/ojoc/commits/

**Comment by asd9** [comment]
Awesome!
Thanks for the quick reply.
