### ISSUE TITLE
Cannot build on Node v6.10.2

### ISSUE THREAD

**Issue by iYsood** [AsamK/JodelJS#4]
Hello all, 

I cannot build NPM on this version, There are something wrong on imageCaptcha.php :(

SyntaxError: ~/JodelJS/src/redux/reducers/imageCaptcha.js: null is a reserved word (6:26)
  4 | export default function imageCaptcha(state = Immutable.Map({
  5 |     key: null,
.> 6 |     image: Immutable.Map({null, null}),
    |.............................................^
  7 | }), action) {
  8 |     switch (action.type) {
  9 |         case SET_IMAGE_CAPTCHA:

,,,

**Comment by AsamK** [comment]
That code is just wrong, it should be {url: null, width: null} instead of {null, null}
I wonder why I haven't seen this error message before.
