### ISSUE TITLE
Seems to only work for Android? 

### ISSUE THREAD

**Issue by Emil8250** [AsamK/JodelJS#5]
When I run the app, and tries to input my iPhones UDID, I get a hex error, is this as intended?

**Comment by AsamK** [comment]
Should work on any modern browser. What's the exact error message that you get?
Also which iOS version do you have? Maybe the app needs some additional shims for older Safari versions.

**Comment by Emil8250** [comment]
Probably just me who’s doing something wrong + my German is really bad. 

I Ticked this box: 
Bestehendes Jodel Konto nutzen
Device UID des bestehenden Kontos: 
In The text field i entered my iPhones UDID, which I found in iTunes, is this correct? 

I connected to The site using Google Chrome on Windows 7

**Comment by AsamK** [comment]
Ah the device id for jodel is a hash of several phone identifiers. For android I have some code in #2 to compute the id, for the iOS version I don't know how it is computed. Using an existing jodel account from iOS would only be possible, if someone reverse engineers the id computation.

**Comment by Emil8250** [comment]
Ahh dang it! Sadly I don’t Have The time to look into it myself, thanks for The Quick and Good replies!
