### ISSUE TITLE
Access denied: Account not verified: 478

### ISSUE THREAD

**Issue by mattias10** [AsamK/JodelJS#6]
Why do I keep getting this?

Do I have to add something in the code that I don't know about? I'm using the most recent HMAC key as far as I know.

**Comment by AsamK** [comment]
There are two ways to verify an account. The "Find the raccoon" images and a verification based on a GCM account. The first one sets the account to verified, but some things, like voting/posting still don't work.
To use the GCM method, JodelJS needs support from a server (For XMPP connection). The server endpoints can be specified in the settings file: GCM_ACCOUNT_HELPER_URL, GCM_RECEIVE_HELPER_URL.
The jodel_api projects provides the necessary methods to implement that server part:
https://github.com/nborrmann/jodel_api#account-verification

**Comment by mattias10** [comment]
Am I supposed to enter my server url (which is my ip address) in both
GCM_ACCOUNT_HELPER_URL
and GCM_RECEIVE_HELPER_URL? Or am I'm understanding it wrong? Cause I feel
like i've tried pretty much everything, but I can't get it to work still.
Sorry for taking up your time

2018-05-11 1:03 GMT+02:00 AsamK <notifications@github.com>:

**Comment by AsamK** [comment]
you'll have to write that server part first. That needs to provide two different endpoints, one that creates a GCM account and another one that receives GCM notifications and returns the verifiation token sent by the jodel server.
I only have a very hack python cgi implementation, based on the `jodel_api` project...
