### ISSUE TITLE
I always get Fehler: 403 Forbidden Forbidden

### ISSUE THREAD

**Issue by Kuinausi** [AsamK/JodelJS#7]
Whenever i press on "Jodeln beginnen", there is an error message: "Fehler: 403 forbidden forbidden"
Why and how can i fix that?

**Comment by AsamK** [comment]
I haven't gotten a 403 Forbidden yet. I usually get a 477 error when trying to register with an old secret.
I've updated the KEY and CLIENT_ID in settings.ts.sample, you can try if registering works when you use those.

**Comment by Kuinausi** [comment]
Works now. Thank you very much.
